# Generated by Django 3.2.13 on 2022-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acertoserros',
            name='erros',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acertoserros',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
    ]
