# Generated by Django 3.2.13 on 2022-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20221011_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='acertoserros',
            name='nivelDoAluno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
