# Generated by Django 3.2 on 2022-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nivelQuestao9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
