# Generated by Django 3.2.13 on 2022-11-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fkTurmas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.turmas'),
        ),
    ]
