# Generated by Django 3.2 on 2022-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220911_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao1',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao10',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao2',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao3',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao4',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao5',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao6',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao7',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao8',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nivelQuestao9',
        ),
        migrations.AlterField(
            model_name='professor',
            name='isProf',
            field=models.BooleanField(default=0),
        ),
    ]
