# Generated by Django 3.2.13 on 2022-11-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_formulario_fkturmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='fkTurmas',
        ),
    ]
