# Generated by Django 3.2.13 on 2022-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20221119_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoesescolhidasaluno',
            name='ano_letivo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='questoesescolhidasaluno',
            name='classe',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
